### ISSUE TITLE
ERROR: ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by Stcetjo** [OutlierVentures/ANVIL#3]
Error:
Using /usr/lib/python3/dist-packages
Finished processing dependencies for oef==0.2.0
Traceback (most recent call last):
  File "scripts/setup_test.py", line 32, in <module>
    from git import Repo, RemoteProgress, InvalidGitRepositoryError
ModuleNotFoundError: No module named 'git'
Error: failed on line 72.

On Ubuntu:
installed Docker
installed python -m pip install pygithub
ran script.

Any ideas?

**Comment by theoturner** [comment]
Please try `pip3 install gitpython`.

**Comment by AronVanAmmers** [comment]
@Stcetjo thanks for submitting this. In addition to @theoturner's suggestion, could you give us some more info on your setup? You mention Ubuntu - which version are you running? Are you using a clean install?

**Comment by Stcetjo** [comment]
> Please try `pip3 install gitpython`.

This worked! 
Had installed 'pip install gitpython' and that did not work

**Comment by theoturner** [comment]
Thanks, added to installer for future.
